### ISSUE TITLE
Question about saving CDERI in CPU memory

### ISSUE THREAD

**Issue by cpeter153** [pyscf/gpu4pyscf#235]
Hello, thank you for this amazing package. I had a question about the feature of saving CDERI in cpu memory. I've been trying to run an scf calculation for a molecule with 116 atoms using PBE0/def2-tzvp:
` 

    mol = gto.M(atom=xyz)
    mol.basis =  "def2-tzvp"
    mol.max_memory = 700000

    mol.build()
    rks = dft.RKS(mol).density_fit()
    rks.xc = "pbe0"

    rks.max_cycle = 50
    rks.grids.level = 3
    rks.conv_tol = 1e-7
    rks.kernel()
`
And this leads to 
"...gpu4pyscf/df/df.py", line 228, in cholesky_eri_gpu raise RuntimeError('Out of CPU memory')
RuntimeError: Out of CPU memory

I'm not sure, but I'm thinking that this is related to the feature of saving CDERI in CPU memory. I did read in description page that one of the limitations is "Density fitting scheme up to ~168 atoms with def2-tzvpd basis, bounded by CPU memory;" but I feel like the molecule that I'm trying to perform the calculation on is still far from that limit (most of the atoms are carbon or hydrogen with less than 5 nitrogen atoms). I've been trying to run this calculation on a system with H100 NVL and cpu ram memory of ~700 Gb.  I guess my question is the cpu memory referring to the ram memory or is referring to something else? How does the feature "saving CDERI in cpu memory" work?

**Comment by wxj6000** [comment]
The CPU memory refers to the ram memory. When the size of CDERI exceeds the GPU memory size, CDERI will be automatically saved in CPU memory (ram memory). In your case, CDERI of 116 atoms should comfortably fit in a system with H100 NVL. 

- Can you provide the xyz of the molecule?

- Can you try the following script to test if the code is running in the environment as expected and the CPU memory is actually available? 
```Python
mem = cupy.cuda.alloc_pinned_memory(50 * 1e9 * 8)
cderi = np.ndarray([50*1024*1024*1024], dtype=np.float64, order='C', buffer=mem)
```

**Comment by cpeter153** [comment]
Thanks for the reply! I've tried your suggestions of allocating pinned memory and I found out that if I try to allocate any amount of memory beyond the gpu memory I get the following error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/cuda/pinned_memory.pyx", line 201, in cupy.cuda.pinned_memory.alloc_pinned_memory
  File "cupy/cuda/pinned_memory.pyx", line 215, in cupy.cuda.pinned_memory.alloc_pinned_memory
  File "cupy/cuda/pinned_memory.pyx", line 289, in cupy.cuda.pinned_memory.PinnedMemoryPool.malloc
  File "cupy/cuda/pinned_memory.pyx", line 309, in cupy.cuda.pinned_memory.PinnedMemoryPool.malloc
  File "cupy/cuda/pinned_memory.pyx", line 306, in cupy.cuda.pinned_memory.PinnedMemoryPool.malloc
  File "cupy/cuda/pinned_memory.pyx", line 180, in cupy.cuda.pinned_memory._malloc
  File "cupy/cuda/pinned_memory.pyx", line 181, in cupy.cuda.pinned_memory._malloc
  File "cupy/cuda/pinned_memory.pyx", line 30, in cupy.cuda.pinned_memory.PinnedMemory.__init__
  File "cupy_backends/cuda/api/runtime.pyx", line 554, in cupy_backends.cuda.api.runtime.hostAlloc
  File "cupy_backends/cuda/api/runtime.pyx", line 146, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorOperatingSystem: OS call failed or operation not supported on this OS
```
The OS of the system is Ubuntu 18.04 and I've been reading on some forums that the outdated kernel (4.15.0) can cause some issues with some of cuda's functionality. Unfortunately, I'm not sure if my admins are able to perform the update. Would you happen to know any workaround for such issue?

**Comment by cpeter153** [comment]
Closing the issue since it seems to be a problem on my end.
