### ISSUE TITLE
pip3 isntall fails....

### ISSUE THREAD

**Issue by abbottjlu** [pyscf/gpu4pyscf#237]
This is what I saw on my Linux box. 

```
(gpu4pyscf) [test2024@gpu01 ~]$ pip3 install gpu4pyscf-cuda12x
Collecting gpu4pyscf-cuda12x
  Could not find a version that satisfies the requirement gpu4pyscf-cuda12x (from versions: )
No matching distribution found for gpu4pyscf-cuda12x
(gpu4pyscf) [test2024@gpu01 ~]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
(gpu4pyscf) [test2024@gpu01 ~]$
```

**Comment by wxj6000** [comment]
Can you try
```
python3 -m pip install --upgrade pip
```
or 
```
pip install --extra-index-url=https://pypi.org/simple gpu4pyscf-cuda12x
```

**Comment by abbottjlu** [comment]
The python env is controlled via conda. 

The first cmd, `python3 -m pip install --upgrade pip`, reports error, 

```
(gpu4pyscf) [test2024@gpu01 ~]$ python3 -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 463kB/s
Installing collected packages: pip
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/pip'
```

The second cmd, `pip3 install --extra-index-url=https://pypi.org/simple gpu4pyscf-cuda12x`, report error, either. 

```
(gpu4pyscf) [test2024@gpu01 ~]$ pip3 install --extra-index-url=https://pypi.org/simple gpu4pyscf-cuda12x
Collecting gpu4pyscf-cuda12x
  Could not find a version that satisfies the requirement gpu4pyscf-cuda12x (from versions: )
No matching distribution found for gpu4pyscf-cuda12x
(gpu4pyscf) [test2024@gpu01 ~]$
```
