### ISSUE TITLE
Error of get_j function in scf.jk

### ISSUE THREAD

**Issue by YuzheZhang98** [pyscf/gpu4pyscf#271]
The get_j function in gpu4pyscf/scf/jk.py https://github.com/pyscf/gpu4pyscf/blob/b7de1647a903635e811b2bba49c5301241856ea2/gpu4pyscf/scf/jk.py#L224 raises CUDA Error in RYS_build_j, but get_jk works just fine. 

Below is a minimum example I used to test it.
```
from pyscf import gto
import numpy as np
from gpu4pyscf.scf.jk import get_jk, get_j

mol = gto.M(atom='H -0.5 0 0; H 0.5 0 0', basis='sto-3g')
nao = mol.nao_nr()
dm = np.random.random((nao, nao))
print(get_jk(mol, dm))
print(get_j(mol, dm))
```
The output of the test code is
```
(array([[0.66437241, 0.35450663],
       [0.35450663, 0.73687943]]), array([[0.5776128 , 0.61728321],
       [0.6241186 , 0.72839951]]))
CUDA Error in RYS_build_j: invalid argument
Traceback (most recent call last):
  File "/home/zhang2539/test/test_j.py", line 9, in <module>
    print(get_j(mol, dm))
          ^^^^^^^^^^^^^^
  File "/home/zhang2539/gpu4pyscf/gpu4pyscf/scf/jk.py", line 335, in get_j
    raise RuntimeError(f'RYS_build_jk kernel for {llll} failed')
RuntimeError: RYS_build_jk kernel for (ss|ss) failed
```

**Comment by YuzheZhang98** [comment]
Updated the code to the newest commit and recompiled it solved the issue.
